"use client";

import { useState } from "react";
import { PublicKey, Transaction } from "@solana/web3.js";
import { buildTokenLaunchTransaction } from "../../lib/token-launch-transaction";
import { confirmSignature } from "../../lib/solana-confirm";
const RPC = process.env.NEXT_PUBLIC_SOLANA_RPC_URL || "https://api.devnet.solana.com";
const CLUSTER = process.env.NEXT_PUBLIC_SOLANA_CLUSTER || "devnet";
type Wallet = { publicKey?: PublicKey | null; signTransaction?: (tx: Transaction) => Promise<Transaction> };
function getWallet(): Wallet { return (window as Window & { solana?: Wallet }).solana || {}; }
export function TokenLaunchSigner() {
  const [name,setName]=useState(""); const [symbol,setSymbol]=useState(""); const [description,setDescription]=useState(""); const [image,setImage]=useState(""); const [website,setWebsite]=useState(""); const [twitter,setTwitter]=useState(""); const [telegram,setTelegram]=useState(""); const [status,setStatus]=useState("idle"); const [error,setError]=useState(""); const [mint,setMint]=useState("");
  async function launch() { const wallet=getWallet(); if(!wallet.publicKey||!wallet.signTransaction){setError("Connect a Solana wallet first.");return;} setError(""); setStatus("preparing"); try { const metadataResponse=await fetch("/api/metadata/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,symbol,description,image,website,twitter,telegram})}); const metadata=await metadataResponse.json() as {uri?:string;error?:string}; if(!metadataResponse.ok||!metadata.uri) throw new Error(metadata.error||"Unable to prepare metadata"); const prepared=await fetch("/api/launch/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,symbol,uri:metadata.uri,payer:wallet.publicKey.toBase58()})}); const data=await prepared.json() as {transaction?:string;mint?:string;lastValidBlockHeight?:number;error?:string}; if(!prepared.ok||!data.transaction||!data.mint||typeof data.lastValidBlockHeight!=="number") throw new Error(data.error||"Unable to prepare token launch"); setStatus("signing"); const signed=await wallet.signTransaction(Transaction.from(Buffer.from(data.transaction,"base64"))); setStatus("confirming"); const {Connection}=await import("@solana/web3.js"); const connection=new Connection(RPC,"confirmed"); const signature=await connection.sendRawTransaction(signed.serialize(),{skipPreflight:false,preflightCommitment:"confirmed",maxRetries:3}); await confirmSignature(connection,signature,data.lastValidBlockHeight); setMint(data.mint); setStatus("confirmed"); } catch(e){setStatus("failed");setError(e instanceof Error?e.message:"Launch failed");} }
  return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#f5c542]">{CLUSTER === "mainnet-beta" ? "Mainnet" : CLUSTER} Fair Launch</p><h3 className="mt-2 text-xl font-black">Create → initialize → developer buy</h3><p className="mt-2 text-sm leading-6 text-white/45">FORGE X stores real metadata on public IPFS, creates the fixed 1B token, locks authorities, initializes the curve, seeds its vault, then requires and verifies the developer&apos;s 0.5 SOL first buy.</p></div><div className="grid gap-3 sm:grid-cols-2"><input value={name} onChange={(e)=>setName(e.target.value)} className="forge-input" placeholder="Token name" maxLength={32}/><input value={symbol} onChange={(e)=>setSymbol(e.target.value.toUpperCase())} className="forge-input" placeholder="SYMBOL" maxLength={10}/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} className="forge-input sm:col-span-2" placeholder="Description"/><input value={image} onChange={(e)=>setImage(e.target.value)} className="forge-input" placeholder="Image URL"/><input value={website} onChange={(e)=>setWebsite(e.target.value)} className="forge-input" placeholder="Website"/><input value={twitter} onChange={(e)=>setTwitter(e.target.value)} className="forge-input" placeholder="X / Twitter"/><input value={telegram} onChange={(e)=>setTelegram(e.target.value)} className="forge-input" placeholder="Telegram"/></div><button onClick={launch} disabled={status!=="idle"&&status!=="failed"&&status!=="confirmed"} className="mt-5 w-full rounded-xl bg-[#f5c542] py-3 font-bold text-black disabled:opacity-40">{status==="preparing"?"Preparing…":status==="signing"?"Approve in wallet…":status==="confirming"?"Confirming…":status==="confirmed"?"Launch confirmed ✓":"Create Fair Launch"}</button>{mint&&<p className="mt-3 break-all text-xs text-white/50">Mint: {mint}</p>}{error&&<p className="mt-3 text-xs text-red-400">{error}</p>}</div>;
}
