"use client";

import { useEffect, useState } from "react";
import { Connection, PublicKey } from "@solana/web3.js";
const RPC = process.env.NEXT_PUBLIC_SOLANA_RPC_URL || "https://api.devnet.solana.com"; const CLUSTER = process.env.NEXT_PUBLIC_SOLANA_CLUSTER || "devnet";
type Wallet = { publicKey?: PublicKey | null; connect?: () => Promise<void>; disconnect?: () => Promise<void> }; type TokenPosition = { mint: string; amount: string; decimals: number };
function getWallet(): Wallet | undefined { return (window as Window & { solana?: Wallet }).solana; }
export function WalletPortfolio() {
  const [address, setAddress] = useState(""); const [sol, setSol] = useState(0); const [tokens, setTokens] = useState<TokenPosition[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function load(publicKey: PublicKey) { setAddress(publicKey.toBase58()); setLoading(true); setError(""); try { const connection = new Connection(RPC, "confirmed"); const [balance, accounts] = await Promise.all([connection.getBalance(publicKey, "confirmed"), connection.getParsedTokenAccountsByOwner(publicKey, { programId: new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA") }, "confirmed")]); setSol(balance / 1_000_000_000); const positions = accounts.value.map(({ account }) => { const info = account.data.parsed.info; return { mint: info.mint as string, amount: info.tokenAmount.uiAmountString as string, decimals: info.tokenAmount.decimals as number }; }).filter((position) => position.amount !== "0"); setTokens(positions); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load wallet balances"); } finally { setLoading(false); } }
  async function connect() { const wallet = getWallet(); if (!wallet?.connect) { setError("No compatible browser Solana wallet was detected."); return; } setError(""); try { await wallet.connect(); if (wallet.publicKey) await load(wallet.publicKey); } catch (e) { setError(e instanceof Error ? e.message : "Wallet connection failed"); } }
  useEffect(() => { const current = getWallet()?.publicKey; if (current) void load(current); }, []);
  return !address ? <div className="rounded-2xl border border-white/10 bg-white/[.025] p-8 text-center"><div className="text-5xl">◎</div><h2 className="mt-4 text-xl font-bold">Connect your Solana wallet</h2><p className="mx-auto mt-2 max-w-md text-sm text-white/45">FORGE X reads balances directly from Solana RPC. No private keys are requested or stored.</p><button onClick={connect} className="mt-5 rounded-full bg-[#f5c542] px-6 py-3 font-bold text-black">Connect Wallet</button>{error && <p className="mt-3 text-xs text-red-300">{error}</p>}</div> : <div className="space-y-5"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.2em] text-[#f5c542]">Wallet</p><p className="mt-2 break-all text-sm text-white/60">{address}</p></div><button onClick={() => { const current = getWallet()?.publicKey; if (current) void load(current); }} disabled={loading} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold disabled:opacity-40">{loading ? "Refreshing…" : "Refresh"}</button></div><p className="mt-5 text-3xl font-black">{sol.toFixed(4)} SOL</p><p className="mt-1 text-xs uppercase tracking-widest text-white/30">{CLUSTER}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><h2 className="text-xl font-black">SPL Token positions</h2>{tokens.length === 0 ? <p className="mt-3 text-sm text-white/45">No non-zero legacy SPL Token positions found.</p> : <div className="mt-4 space-y-2">{tokens.map((token) => <div key={token.mint} className="rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-sm font-bold">{token.amount}</p><p className="mt-1 break-all text-xs text-white/35">{token.mint}</p></div>)}</div>}{error && <p className="mt-4 text-xs text-red-300">{error}</p>}</div></div>;
}
