"use client";

import { useEffect, useState } from "react";
import { Connection, PublicKey } from "@solana/web3.js";
const RPC = process.env.NEXT_PUBLIC_SOLANA_RPC_URL || "https://api.devnet.solana.com"; const CLUSTER = process.env.NEXT_PUBLIC_SOLANA_CLUSTER || "devnet"; const FORGE_PROGRAM_ID = process.env.NEXT_PUBLIC_FORGE_X_PROGRAM_ID || "";
const SYSTEM_PROGRAM = "11111111111111111111111111111111"; const TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"; const ASSOCIATED_TOKEN_PROGRAM = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
type Wallet = { publicKey?: PublicKey | null }; type ActivityItem = { signature: string; slot: number; blockTime: number | null; confirmationStatus: string | null; err: unknown; feeLamports: number | null; type: string }; type ParsedInstruction = { programId?: string; program?: string };
function getWallet(): Wallet | undefined { return (window as Window & { solana?: Wallet }).solana; }
function formatTime(timestamp: number | null) { if (!timestamp) return "Time unavailable"; return new Date(timestamp * 1000).toLocaleString(); }
function classify(instructions: ParsedInstruction[]) { const ids = new Set(instructions.map((instruction) => instruction.programId).filter(Boolean)); if (FORGE_PROGRAM_ID && ids.has(FORGE_PROGRAM_ID)) return "FORGE X"; if (ids.has(TOKEN_PROGRAM)) return "Token activity"; if (ids.has(ASSOCIATED_TOKEN_PROGRAM)) return "Token account"; if (ids.has(SYSTEM_PROGRAM)) return "SOL transfer"; return "Transaction"; }
export function WalletActivity() {
  const [address, setAddress] = useState(() => { if (typeof window === "undefined") return ""; return getWallet()?.publicKey?.toBase58() || ""; }); const [items, setItems] = useState<ActivityItem[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function load(publicKey: PublicKey) { setLoading(true); setError(""); try { const connection = new Connection(RPC, "confirmed"); const signatures = await connection.getSignaturesForAddress(publicKey, { limit: 12 }, "confirmed"); const details = await Promise.all(signatures.map(async (item) => { try { const transaction = await connection.getTransaction(item.signature, { commitment: "confirmed", maxSupportedTransactionVersion: 0, encoding: "jsonParsed" }); const instructions = (transaction?.transaction.message.instructions ?? []) as ParsedInstruction[]; return { signature: item.signature, slot: item.slot, blockTime: item.blockTime, confirmationStatus: item.confirmationStatus ?? null, err: item.err, feeLamports: transaction?.meta?.fee ?? null, type: classify(instructions) }; } catch { return { signature: item.signature, slot: item.slot, blockTime: item.blockTime, confirmationStatus: item.confirmationStatus ?? null, err: item.err, feeLamports: null, type: "Transaction" }; } })); setItems(details); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load wallet activity"); } finally { setLoading(false); } }
  useEffect(() => { const current = getWallet()?.publicKey; if (current) void load(current); }, []);
  if (!address) return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><p className="text-xs uppercase tracking-[.2em] text-[#f5c542]">Activity</p><h2 className="mt-1 text-xl font-black">Transaction history</h2><p className="mt-2 text-sm text-white/45">Connect your wallet above to load confirmed transaction history directly from Solana RPC.</p></div>;
  return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.2em] text-[#f5c542]">Activity</p><h2 className="mt-1 text-xl font-black">Transaction history</h2><p className="mt-1 break-all text-xs text-white/35">{address}</p></div><button type="button" onClick={() => { const current = getWallet()?.publicKey; if (current) void load(current); }} disabled={loading} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold disabled:opacity-40">{loading ? "Refreshing…" : "Refresh"}</button></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<div className="mt-5 space-y-2">{items.length === 0 && !loading ? <p className="text-sm text-white/45">No confirmed transactions found.</p> : items.map((item) => <div key={item.signature} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-bold">{item.type}</span><span className={`text-xs font-bold ${item.err ? "text-red-300" : "text-emerald-300"}`}>{item.err ? "Failed" : "Confirmed"}</span></div><p className="mt-2 text-xs text-white/40">{formatTime(item.blockTime)} · slot {item.slot}{item.feeLamports !== null ? ` · fee ${(item.feeLamports / 1_000_000_000).toFixed(6)} SOL` : ""}</p><a className="mt-2 block break-all text-xs text-[#f5c542]" href={CLUSTER === "mainnet-beta" ? `https://solscan.io/tx/${item.signature}` : `https://solscan.io/tx/${item.signature}?cluster=${CLUSTER}`} target="_blank" rel="noreferrer">{item.signature}</a></div>)}</div></div>;
}
